import Footer from "@/components/ui/layout/Footer";
import Navbar from "@/components/ui/layout/Navbar";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import { Toaster } from "sonner";
import ConditionalLayout from "./ConditionalLayout";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Codinism",
  description: "Generated by create next app",
  icons: {
    icon: { url: "/favicon.png", type: "image/png" },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#000102]`}
        suppressHydrationWarning
      >
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-D1B2WMRFZG"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-D1B2WMRFZG');
          `}
        </Script>
        <div className="w-full sticky top-0  z-50 bg-[#000102]">
          <Navbar />
        </div>
        <section className="max-w-[1400px] mx-auto">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ConditionalLayout>
              <Toaster richColors position="top-right" />
              {children}
            </ConditionalLayout>
          </ThemeProvider>
        </section>
        <Footer />
      </body>
    </html>
  );
}
